### ISSUE TITLE
Failed to compile regex error

### ISSUE THREAD

**Issue by N4M3Z** [oknowton/zsh-dwim#6]
Hi, I am getting an error upon pressing control+u:
```
_dwim_transform:6: failed to compile regex: repetition-operator operand invalid
```
My zsh version is 5.0.7 (x86_64-apple-darwin14.0.0).

**Comment by oknowton** [comment]
The error message wasn't quite enough info to pinpoint the precise location of the problem, but I think I've made a guess as to which transforms are the most probably culprits.

The chmod and chattr transforms had some regexes that look like '^chattr.*+'.  I'm guessing that your zsh and/or regex libraries dislike the '*+', and to be honest, I'm surprised they work anywhere.  I've added the appropriate escapes and pushed up the changes.

With any luck, this was actually the problem!

**Comment by N4M3Z** [comment]
Thanks, it's working now. Sorry, but that was the full error message I got. Otherwise I would have to dig in the functions.

**Comment by oknowton** [comment]
I'm glad to hear that it is working now!  The error message was as clear as I could hope for.  That line number in that loop goes through about 50 different pieces of data, and any one of them could have been causing a problem.

I'm just glad that it was obvious.  I have no idea what the best way of actually tracking down that bug on your machine would have been!

Thanks for the bug report!
