### ISSUE TITLE
Code help

### ISSUE THREAD

**Issue by srijanshetty** [oknowton/zsh-dwim#9]
Could you explain what this line does exactly?
https://github.com/oknowton/zsh-dwim/blob/master/transform.d/ls.zsh#L17

**Comment by oknowton** [comment]
http://zsh.sourceforge.net/Guide/zshguide05.html

(q) and (Q) are in section 5.1.1 there.  They're used to strip backslashes and quoting.  The real question would probably be why I actually had to use it.  I'm guessing that the quoting needed to be stripped out for the `-d` to work.

It would be nice if we could get the shell to split up the command line into parameters for us just like it does when executing a command, but I'm not sure if that would be possible.

**Comment by srijanshetty** [comment]
@oknowton : Thanks for that.
